### ISSUE TITLE
修复Scheduler::Stop

### ISSUE THREAD

**Issue by Haovvu** [Haovvu/sylar-study#11]
处理rootCoroutine的stop逻辑

**Comment by Linkvvu** [comment]
Resolved by: https://github.com/Haovvu/sylar-study/blob/d8ed39458cebf44d994dc5c84a3425a6ea9468d5/sylar/concurrency/scheduler.cpp#L81-L112
https://github.com/Haovvu/sylar-study/blob/d8ed39458cebf44d994dc5c84a3425a6ea9468d5/sylar/concurrency/coroutine.cpp#L160-L170
https://github.com/Haovvu/sylar-study/blob/d8ed39458cebf44d994dc5c84a3425a6ea9468d5/sylar/concurrency/coroutine.cpp#L177-L189
